//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_QLHocSinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class GiaoVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaoVien()
        {
            this.LichGiangDay = new HashSet<LichGiangDay>();
        }

        [DisplayName("Mã giáo viên")]
        [StringLength(10)]
        public string MaGV { get; set; }

        [DisplayName("Tên giáo viên")]
        [Required(ErrorMessage = "Họ tên là bắt buộc.")]
        [StringLength(20)]
        public string HoTen { get; set; }

        [DisplayName("Giới tính")]
        [Required(ErrorMessage = "Vui lòng chọn giới tính.")]
        public bool GioiTinh { get; set; }

        [DisplayName("Ngày sinh")]
        [Required(ErrorMessage = "Ngày sinh là bắt buộc.")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime NgaySinh { get; set; }

        [DisplayName("Địa chỉ")]
        [Required(ErrorMessage = "Địa chỉ là bắt buộc.")]
        [StringLength(50)]
        public string DiaChi { get; set; }

        [EmailAddress(ErrorMessage = "Email không hợp lệ.")]
        [Required(ErrorMessage = "Email là bắt buộc.")]
        [StringLength(30)]
        public string Email { get; set; }

        [DisplayName("Số điện thoại")]
        [Required(ErrorMessage = "Số điện thoạilà bắt buộc.")]
        [StringLength(10)]
        public string SDT { get; set; }

        public string MaCV { get; set; }

        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Mật khẩu là bắt buộc.")]
        [StringLength(20)]
        public string Pass { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichGiangDay> LichGiangDay { get; set; }
    }
}
