//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_QLHocSinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KhoiLop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhoiLop()
        {
            this.LopHoc = new HashSet<LopHoc>();
        }

        [DisplayName("Mã khối lớp")]
        [StringLength(2, ErrorMessage = "Mã khối chỉ có thể chứa 2 ký tự.")]
        [Required(ErrorMessage = "Mã khối lớp là bắt buộc")]
        public string MaKL { get; set; }

        [DisplayName("Tên khối lớp")]
        [Required(ErrorMessage = "Tên khối lớp là bắt buộc")]
        [StringLength(20, ErrorMessage = "Tên khối chỉ có thể chứa 20 ký tự.")]
        public string TenKL { get; set; }

        [DisplayName("Mô tả")]
        [StringLength(100, ErrorMessage = "Mô tả chỉ có thể chứa 100 ký tự.")]
        public string MoTa { get; set; }

        [DisplayName("Cấp bậc")]
        [Required(ErrorMessage = "Cấp bậc là bắt buộc")]
        public int CapBac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHoc> LopHoc { get; set; }
    }
}
