//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_QLHocSinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LichGiangDay
    {
        [DisplayName("Lớp")]
        [Required(ErrorMessage = "Vui lòng chọn lớp học")]
        public string MaLop { get; set; }

        [DisplayName("Môn")]
        [Required(ErrorMessage = "Vui lòng chọn môn học")]
        public string MaMH { get; set; }

        [DisplayName("Giáo viên")]
        [Required(ErrorMessage = "Vui lòng chọn giáo viên")]
        public string MaGV { get; set; }

        [DisplayName("Ca")]
        [Required(ErrorMessage = "Vui lòng chọn ca")]
        public string MaCa { get; set; }

        public virtual CaHoc CaHoc { get; set; }
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual LopHoc LopHoc { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
