//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_QLHocSinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHoc()
        {
            this.HocSinh = new HashSet<HocSinh>();
            this.LichGiangDay = new HashSet<LichGiangDay>();
            this.BangDiem = new HashSet<BangDiem>();
        }

        [DisplayName("Mã lớp")]
        [Required(ErrorMessage = "Mã lớp là bắt buộc")]
        [StringLength(2, ErrorMessage = "Mã lớp chỉ có thể chứa 2 ký tự.")]
        public string MaLop { get; set; }

        [DisplayName("Tên lớp")]
        [Required(ErrorMessage = "Tên lớp là bắt buộc.")]
        [StringLength(20, ErrorMessage = "Tên lớp không thể dài quá 20 ký tự.")]
        public string TenLop { get; set; }

        [DisplayName("Mô tả")]
        [StringLength(100, ErrorMessage = "Mô tả không thể dài quá 100 ký tự.")]
        public string MoTa { get; set; }

        public string MaKL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocSinh> HocSinh { get; set; }
        public virtual KhoiLop KhoiLop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichGiangDay> LichGiangDay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangDiem> BangDiem { get; set; }
    }
}
